name: Deploy Vercel Bot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Vercel bot
        run: npm run build
      - name: Deploy Vercel bot
        run: vercel deploy --prebuilt
